### ISSUE TITLE
put this repo info in your profile bio

### ISSUE THREAD

**Issue by Hydrogen8** [rallypoint99/rallypoint99#1]
**that's what it's for**

**Comment by rallypoint99** [comment]
Idk?

**Comment by Hydrogen8** [comment]
go to [profile settings](https://github.com/settings/profile/) and edit the `Bio` section.

**Comment by Hydrogen8** [comment]
[follow this.](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-profile/managing-your-profile-readme)
